debug:
  false
logging:
  level:
    cn.kd: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

spring:
  datasource:
    url: jdbc:mysql://39.96.216.143:3306/external?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 500
      pool-name: MySqlHikariCP
      connection-test-query: SELECT 1


